api_platform:
    #global configuration defaults applied to all resources and all operations (2.6 only)
    defaults:
        #By default, API Platform generates all URLs as absolute paths to the base URL.
        url_generation_strategy: !php/const ApiPlatform\Api\UrlGeneratorInterface::ABS_PATH
        pagination_client_enabled: true #Enabling Pagination Client-side Globally
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 1000
        pagination_items_per_page: 30
        item_Operations: ~
        collection_Operations: ~
        normalization_context:
            # Default value to omit null values in conformance with the JSON Merge Patch RFC.
            skip_null_values: false
    # The title of the API.
    title: 'Episciences API'
    # The description of the API.
    description: 'Search API'
    # The version of the API.
    version: "%git_application_version%"

    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        xml: ['application/xml']

    # Set this to false if you want Webby to disappear.
    show_webby: false
    #Since api-platform/core 3.3: Setting the value of "use_symfony_listeners" will be mandatory in 4.0 as it will default to "false".
    #Use "true" if you use Symfony Controllers or Event Listeners.
    use_symfony_listeners: true
    openapi:
        # The contact information for the exposed API.
        contact:
            # The identifying name of the contact person/organization.
            name:
            # The URL pointing to the contact information. MUST be in the format of a URL.
            url:
            # The email address of the contact person/organization. MUST be in the format of an email address.
            email:
        # A URL to the Terms of Service for the API. MUST be in the format of a URL.
        termsOfService: https://www.episciences.org/terms-of-use/
        # The license information for the exposed API.
        license:
            # The license name used for the API.
            name:
            # URL to the license used for the API. MUST be in the format of a URL.
            url:

    mapping:
        # The list of paths with files or directories where the bundle will look for additional resource files.
        paths: ['%kernel.project_dir%/src/Resource']

        # The list of your resources class directories. Defaults to the directories of the mapping paths but might differ.
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    keep_legacy_inflector: false
    exception_to_status:
        # Custom mapping
        App\Exception\ResourceNotFoundException : 404