doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                mapping_types:
                    enum: string
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'
                charset: utf8mb4

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: default
        #Since doctrine/doctrine-bundle 2.12: The default value of "doctrine.orm.controller_resolver.auto_mapping" will be changed from `true` to `false`.
        #Explicitly configure `true` to keep existing behaviour.
        controller_resolver:
            auto_mapping: true
        # Enables the new implementation of proxies based on lazy ghosts instead of using the legacy implementation
        enable_lazy_ghost_objects: true
        entity_managers:
            default:
                connection: default
                # Opt-in to new mapping driver mode as of Doctrine ORM 2.16, https://github.com/doctrine/orm/pull/10455
                report_fields_where_declared: true
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    string_functions:
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract


