monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        deprecation:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            max_files: 5
            level: info
            date-format: 'Y-m-d'
            channels: [deprecation]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@staging:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                max_files: 5
                level: info
                date-format: 'Y-m-d'

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                grouped:
                    type: group
                    members: [streamed] # eg. members: [streamed, swift]
                streamed:
                    type: rotating_file
                    path: "%kernel.logs_dir%/%kernel.environment%.log"
                    max_files: 10
                    level: error
                    date_format: 'Y-m-d'
#                swift:
#                    type: swift_mailer
#                    from_email: 'alert@project.net'
#                    to-email: 'ops@company.net'
#                    subject: 'Critical error'
#                    level: critical

