nelmio_solarium:
    endpoints:
        default:
            host: "%env(SOLR_HOST)%"
            core: "%env(SOLR_CORE)%"
            # The following are the default parameters for Solarium client:
            # scheme: http
            # port: 8983
            # path: /solr
    clients:
        default:
            endpoints: [default]
            # You can customize the http timeout (in seconds) here. The default is 5sec.
            # adapter_timeout: 5
