services:
  php:
    build: ./docker/php-fpm
    container_name: episciences_php
    user: "${DOCKER_USER:-www}"
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    depends_on: []
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - DATABASE_URL=mysql://episciences:episciences@db-episciences:3306/episciences
    networks:
      - epi-network

  apache:
    build: ./docker/apache
    container_name: episciences_apache
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./docker/apache/vhost.conf:/usr/local/apache2/conf/vhost.conf
      - ./docker/apache/vhost-ssl.conf:/usr/local/apache2/conf/vhost-ssl.conf
      - ./docker/apache/ssl:/usr/local/apache2/conf/ssl
    depends_on:
      - php
    networks:
      - epi-network


networks:
  epi-network:
    external: true
    name: episciences-gpl_epi-network