# As of Symfony 5.1, deprecations are logged in the dedicated "deprecation" channel when it exists
monolog:
    handlers:
        deprecation:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            max_files: 5
            level: info
            date-format: 'Y-m-d'
            channels: [ deprecation ]
