monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            grouped:
                type: group
                members: [streamed] # eg. members: [streamed, swift]
            streamed:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                max_files: 10
                level: error
                date-format: 'Y-m-d'
#            swift:
#                type: swift_mailer
#                from_email: 'alert@project.net'
#                to-email: 'ops@company.net'
#                subject: 'Critical error'
#                level: critical
