---
- name: Deploy Episciences API
  hosts: all
  gather_facts: true
  vars:
    ansistrano_after_symlink_shared_paths_tasks_file: "{{ playbook_dir }}/hooks/after-symlink-shared.yml"
    ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/hooks/before-symlink.yml"

  roles:
    - role: ansistrano.deploy
